# config.py

LIVE_MODE = False  # Set to True to enable live trading
SECRET_KEY = ""

ETH_MINT = "7vfCXT4uJzj3qzFqzWgYJzvYk1zFfWzvYk1zFfWzvYk1zFfWzvYk1zFfWzvYk1zFfWzvYk1zFfWzvYk1zFfWzvYk1zFfWzvYk1zFfWzvYk1zFfWzvYk1zFfWzvYk1zFfWzvYk1zFfWzvYk1zFfWzvYk1zFfWzvYk1zFfWzvYk1zFfWzvYk1zFfWzvYk1zFfWzvYk1zFfWzvYk1zFfWzvYk1zFfWzvYk1z
